TAKING ME
[{u'calltype': u'amd64', u'realsz': 189, u'diff': u'NEW', u'name': u'sym.main', u'outdegree': 7, u'cc': 3, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4223149, u'at': 4222992}], u'edges': 7, u'difftype': u'new', u'nlocals': 8, u'cost': 64, u'datarefs': [6341424, 2000, 4234192], u'callrefs': [{u'type': u'C', u'addr': 4226480, u'at': 4223037}, {u'type': u'C', u'addr': 4226480, u'at': 4223078}, {u'type': u'C', u'addr': 4222448, u'at': 4223126}, {u'type': u'C', u'addr': 4223168, u'at': 4223149}, {u'type': u'C', u'addr': 4222608, u'at': 4223174}, {u'type': u'C', u'addr': 4223200, u'at': 4223107}, {u'type': u'C', u'addr': 4223296, u'at': 4223144}], u'offset': 4222992, u'ebbs': 1, u'nbbs': 6, u'type': u'sym', u'size': 197}]
ERR. Target function sym.main0 does not match sym.main
Failed to patch all expected patches: 21  total patched: 42
