TAKING ME
[{u'calltype': u'amd64', u'realsz': 144, u'diff': u'NEW', u'name': u'sym.sig_handler', u'outdegree': 5, u'cc': 1, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4225552, u'at': 4225456}], u'edges': 0, u'difftype': u'new', u'nlocals': 7, u'cost': 46, u'datarefs': [4240591, 4240602], u'callrefs': [{u'type': u'C', u'addr': 4232800, u'at': 4225503}, {u'type': u'C', u'addr': 4232800, u'at': 4225544}, {u'type': u'C', u'addr': 4225568, u'at': 4225552}, {u'type': u'C', u'addr': 4223488, u'at': 4225574}, {u'type': u'C', u'addr': 4223584, u'at': 4225584}], u'offset': 4225456, u'ebbs': 1, u'nbbs': 1, u'type': u'sym', u'size': 144}]
ERR. Target function sym.sig_handler0 does not match sym.sig_handler
Failed to patch all expected patches: 141  total patched: 282
