TAKING ME
[{u'calltype': u'amd64', u'realsz': 96, u'diff': u'NEW', u'name': u'sym.sig_handler', u'outdegree': 4, u'cc': 1, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4229831, u'at': 4229776}], u'edges': 0, u'difftype': u'new', u'nlocals': 4, u'cost': 36, u'datarefs': [4300767, 4300778], u'callrefs': [{u'type': u'C', u'addr': 4292976, u'at': 4229823}, {u'type': u'C', u'addr': 4229840, u'at': 4229831}, {u'type': u'C', u'addr': 4226720, u'at': 4229846}, {u'type': u'C', u'addr': 4226816, u'at': 4229856}], u'offset': 4229776, u'ebbs': 1, u'nbbs': 1, u'type': u'sym', u'size': 96}]
ERR. Target function sym.sig_handler0 does not match sym.sig_handler
Failed to patch all expected patches: 69  total patched: 381
