TAKING ME
[{u'calltype': u'amd64', u'realsz': 384, u'diff': u'NEW', u'name': u'sym.audio_play', u'cc': 7, u'indegree': 0, u'nargs': 0, u'difftype': u'new', u'edges': 19, u'outdegree': 12, u'nlocals': 14, u'cost': 136, u'datarefs': [16, 12, 32, 24, 6467188, 4301111, 6467184, 4301111], u'callrefs': [{u'type': u'C', u'addr': 4288224, u'at': 4248918}, {u'type': u'C', u'addr': 4288224, u'at': 4248959}, {u'type': u'C', u'addr': 4239424, u'at': 4248983}, {u'type': u'C', u'addr': 4249472, u'at': 4249168}, {u'type': u'C', u'addr': 6468384, u'at': 4249215}, {u'type': u'J', u'addr': 4249046, u'at': 4249020}, {u'type': u'C', u'addr': 4249504, u'at': 4249033}, {u'type': u'C', u'addr': 4249616, u'at': 4249041}, {u'type': u'C', u'addr': 4249632, u'at': 4249152}, {u'type': u'C', u'addr': 4239808, u'at': 4249124}, {u'type': u'C', u'addr': 4239760, u'at': 4249143}, {u'type': u'C', u'addr': 4239808, u'at': 4249077}, {u'type': u'C', u'addr': 4239760, u'at': 4249096}], u'offset': 4248864, u'ebbs': 2, u'nbbs': 14, u'type': u'sym', u'size': 386}]
ERR. Target function sym.say_phones1 does not match sym.audio_play
Failed to patch all expected patches: 90  total patched: 180
