TAKING ME
[{u'calltype': u'amd64', u'realsz': 312, u'diff': u'NEW', u'name': u'sym.main', u'outdegree': 10, u'cc': 3, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4223277, u'at': 4222992}], u'edges': 7, u'difftype': u'new', u'nlocals': 17, u'cost': 91, u'datarefs': [6341424, 2000, 4234512], u'callrefs': [{u'type': u'C', u'addr': 4226800, u'at': 4223037}, {u'type': u'C', u'addr': 4226800, u'at': 4223078}, {u'type': u'C', u'addr': 4226800, u'at': 4223119}, {u'type': u'C', u'addr': 4226800, u'at': 4223160}, {u'type': u'C', u'addr': 4226800, u'at': 4223201}, {u'type': u'C', u'addr': 4222448, u'at': 4223254}, {u'type': u'C', u'addr': 4223296, u'at': 4223277}, {u'type': u'C', u'addr': 4222608, u'at': 4223302}, {u'type': u'C', u'addr': 4223328, u'at': 4223235}, {u'type': u'C', u'addr': 4223424, u'at': 4223272}], u'offset': 4222992, u'ebbs': 1, u'nbbs': 6, u'type': u'sym', u'size': 325}]
ERR. Target function sym.main0 does not match sym.main
Failed to patch all expected patches: 42  total patched: 84
