TAKING ME
[{u'calltype': u'amd64', u'realsz': 343, u'diff': u'NEW', u'name': u'sym.audio_play', u'cc': 7, u'indegree': 0, u'nargs': 0, u'difftype': u'new', u'edges': 19, u'outdegree': 11, u'nlocals': 11, u'cost': 127, u'datarefs': [16, 12, 32, 24, 6471284, 4306967, 6471280, 4306967], u'callrefs': [{u'type': u'C', u'addr': 4294080, u'at': 4249718}, {u'type': u'C', u'addr': 4239424, u'at': 4249742}, {u'type': u'C', u'addr': 4250368, u'at': 4249936}, {u'type': u'C', u'addr': 6472480, u'at': 4249983}, {u'type': u'J', u'addr': 4249814, u'at': 4249779}, {u'type': u'C', u'addr': 4250400, u'at': 4249801}, {u'type': u'C', u'addr': 4250512, u'at': 4249809}, {u'type': u'C', u'addr': 4250528, u'at': 4249920}, {u'type': u'C', u'addr': 4239808, u'at': 4249892}, {u'type': u'C', u'addr': 4239760, u'at': 4249911}, {u'type': u'C', u'addr': 4239808, u'at': 4249845}, {u'type': u'C', u'addr': 4239760, u'at': 4249864}], u'offset': 4249664, u'ebbs': 2, u'nbbs': 14, u'type': u'sym', u'size': 354}]
ERR. Target function sym.say_phones1 does not match sym.audio_play
Failed to patch all expected patches: 456  total patched: 912
