TAKING ME
[{u'calltype': u'amd64', u'realsz': 435, u'diff': u'NEW', u'name': u'sym.main', u'outdegree': 13, u'cc': 3, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4223389, u'at': 4222992}], u'edges': 7, u'difftype': u'new', u'nlocals': 26, u'cost': 118, u'datarefs': [6341424, 2000, 4235136], u'callrefs': [{u'type': u'C', u'addr': 4227424, u'at': 4223037}, {u'type': u'C', u'addr': 4227424, u'at': 4223078}, {u'type': u'C', u'addr': 4227424, u'at': 4223119}, {u'type': u'C', u'addr': 4227424, u'at': 4223160}, {u'type': u'C', u'addr': 4227424, u'at': 4223201}, {u'type': u'C', u'addr': 4227424, u'at': 4223242}, {u'type': u'C', u'addr': 4227424, u'at': 4223283}, {u'type': u'C', u'addr': 4227424, u'at': 4223324}, {u'type': u'C', u'addr': 4222448, u'at': 4223366}, {u'type': u'C', u'addr': 4223408, u'at': 4223389}, {u'type': u'C', u'addr': 4222608, u'at': 4223414}, {u'type': u'C', u'addr': 4223440, u'at': 4223347}, {u'type': u'C', u'addr': 4223536, u'at': 4223384}], u'offset': 4222992, u'ebbs': 1, u'nbbs': 6, u'type': u'sym', u'size': 437}]
ERR. Target function sym.main0 does not match sym.main
Failed to patch all expected patches: 81  total patched: 162
