TAKING ME
[{u'calltype': u'amd64', u'realsz': 148, u'diff': u'NEW', u'name': u'sym.main', u'outdegree': 6, u'cc': 3, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4223101, u'at': 4222992}], u'edges': 7, u'difftype': u'new', u'nlocals': 5, u'cost': 55, u'datarefs': [6341424, 2000, 4234128], u'callrefs': [{u'type': u'C', u'addr': 4226416, u'at': 4223037}, {u'type': u'C', u'addr': 4222448, u'at': 4223078}, {u'type': u'C', u'addr': 4223120, u'at': 4223101}, {u'type': u'C', u'addr': 4222608, u'at': 4223126}, {u'type': u'C', u'addr': 4223152, u'at': 4223059}, {u'type': u'C', u'addr': 4223248, u'at': 4223096}], u'offset': 4222992, u'ebbs': 1, u'nbbs': 6, u'type': u'sym', u'size': 149}]
ERR. Target function sym.main0 does not match sym.main
Failed to patch all expected patches: 18  total patched: 36
