TAKING ME
[{u'calltype': u'amd64', u'realsz': 297, u'diff': u'NEW', u'name': u'sym.audio_play', u'cc': 7, u'indegree': 0, u'nargs': 0, u'difftype': u'new', u'edges': 19, u'outdegree': 10, u'nlocals': 8, u'cost': 116, u'datarefs': [16, 12, 32, 24, 6467188, 4300999, 6467184, 4300999], u'callrefs': [{u'type': u'C', u'addr': 4239424, u'at': 4248752}, {u'type': u'C', u'addr': 4249296, u'at': 4248944}, {u'type': u'C', u'addr': 6468384, u'at': 4248991}, {u'type': u'J', u'addr': 4248822, u'at': 4248789}, {u'type': u'C', u'addr': 4249328, u'at': 4248809}, {u'type': u'C', u'addr': 4249440, u'at': 4248817}, {u'type': u'C', u'addr': 4249456, u'at': 4248928}, {u'type': u'C', u'addr': 4239808, u'at': 4248900}, {u'type': u'C', u'addr': 4239760, u'at': 4248919}, {u'type': u'C', u'addr': 4239808, u'at': 4248853}, {u'type': u'C', u'addr': 4239760, u'at': 4248872}], u'offset': 4248720, u'ebbs': 2, u'nbbs': 14, u'type': u'sym', u'size': 306}]
ERR. Target function sym.say_phones1 does not match sym.audio_play
Failed to patch all expected patches: 78  total patched: 156
